# FINTECH Lecture 7

# numpy

In [1]:
import numpy as np

# 1 dimensional Array

In [6]:
a = np.array( [1,2,3] )
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
# 几乘以及的矩阵
a.shape

(3,)

In [9]:
# 几维
a.ndim

1

In [10]:
# 大list有几个元素
len(a)

3

# 2 dimensional Array

In [3]:
B = np.array( [[1,2,3], [2,3,4]] )

In [4]:
B.itemsize

4

In [15]:
B.dtype

dtype('int32')

In [16]:
B[ 1][2 ]

4

In [17]:
B[0,1]

2

In [22]:
C = np.array( [[ 3,6, 9 ]] )
C

array([[3, 6, 9]])

In [19]:
C.ndim

2

In [15]:
D = np.array( [ [ 5 ], [ 10 ] ] )

In [21]:
D

array([[ 5],
       [10]])

In [23]:
#axis = 1 是横着拼，axis = 0 是竖着拼
np.concatenate((B,D),axis = 1)

array([[ 1,  2,  3,  5],
       [ 2,  3,  4, 10]])

In [24]:
np.append(B,C)

array([1, 2, 3, 2, 3, 4, 3, 6, 9])

In [25]:
np.insert(B,2,[10,7],axis = 1)

array([[ 1,  2, 10,  3],
       [ 2,  3,  7,  4]])

In [11]:
C = np.insert( B, 1, [3], axis = 0 )
C

array([[1, 2, 3],
       [3, 3, 3],
       [2, 3, 4]])

# Array Multiplication

In [12]:
A = np.insert( B, 1, [3,3,9], axis = 0 )
A

array([[1, 2, 3],
       [3, 3, 9],
       [2, 3, 4]])

In [13]:
# 对位乘法，不是线代的乘法
A*C

array([[ 1,  4,  9],
       [ 9,  9, 27],
       [ 4,  9, 16]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#向量乘法
A.dot(np.ones((3,3)))

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [ 9.,  9.,  9.]])

In [22]:
# 向量乘法
A@C

array([[13, 17, 21],
       [30, 42, 54],
       [19, 25, 31]])

In [19]:
A+C

array([[ 2,  4,  6],
       [ 6,  6, 12],
       [ 4,  6,  8]])

# Matrix Inverse

In [24]:
#求逆矩阵
A_inv = np.linalg.inv( A )
A_inv

array([[-2.50000000e+00,  1.66666667e-01,  1.50000000e+00],
       [ 1.00000000e+00, -3.33333333e-01,  8.32667268e-17],
       [ 5.00000000e-01,  1.66666667e-01, -5.00000000e-01]])

In [25]:
# A*A^-1
A_inv.dot(A)

array([[ 1.00000000e+00, -2.22044605e-16, -8.88178420e-16],
       [ 5.55111512e-17,  1.00000000e+00, -5.55111512e-16],
       [-2.22044605e-16, -1.11022302e-16,  1.00000000e+00]])

In [26]:
# 生成单位阵
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Multi Dimension

In [28]:
C = np.array([ [ [1,2], [1,2] ], [ [1,2] ,[1,2] ] ])
C

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [29]:
C.shape

(2, 2, 2)

# Mean and STD

In [31]:
input_000568 = [279.18, 279.00, 279.06, 287.79, 290.50, 298.10, 313.99, 292.40]
input_000858 = [304.12, 308.75, 313.60, 319.76, 320.00, 329.50, 342.65, 333.50]

In [33]:
arrays = np.array([ input_000568, input_000858 ])
arrays

array([[279.18, 279.  , 279.06, 287.79, 290.5 , 298.1 , 313.99, 292.4 ],
       [304.12, 308.75, 313.6 , 319.76, 320.  , 329.5 , 342.65, 333.5 ]])

In [34]:
# 所有的均值
arrays.mean()

305.74375

In [35]:
# 对每一行求均值
arrays.mean(axis = 1)

array([290.0025, 321.485 ])

In [36]:
# 对每一列求均值
arrays.mean(axis = 0)

array([291.65 , 293.875, 296.33 , 303.775, 305.25 , 313.8  , 328.32 ,
       312.95 ])

In [37]:
# 截取矩阵[行，列]
# 这里是二维
arrays[1:2,2:5]

array([[313.6 , 319.76, 320.  ]])

# Relative Return

In [40]:
# [第二行，最后一行]/[第一行，最后一行除外]
rel_ret = arrays[:,1:]/arrays[ :,:-1]-1
rel_ret

array([[-0.00064475,  0.00021505,  0.03128359,  0.00941659,  0.02616179,
         0.05330426, -0.06876015],
       [ 0.01522425,  0.0157085 ,  0.01964286,  0.00075056,  0.0296875 ,
         0.03990895, -0.02670363]])

In [42]:
log_ret = np.log(arrays[:,1:]/arrays[ :,:-1])
log_ret

array([[-0.00064495,  0.00021503,  0.03080424,  0.00937253,  0.02582542,
         0.05193214, -0.07123841],
       [ 0.01510953,  0.0155864 ,  0.01945243,  0.00075028,  0.02925536,
         0.03913316, -0.02706665]])

In [44]:
# 对行求标准差
log_ret.std(axis=1)

array([0.03619437, 0.01983911])

In [45]:
np.std(log_ret,axis=1)

array([0.03619437, 0.01983911])

In [46]:
# 协方差
np.cov(log_ret)

array([[0.00152837, 0.00078439],
       [0.00078439, 0.00045919]])

In [ ]:
# 标准差 ddof是自由度（分母减一）
log_ret.var(axis=1,ddof=1)

In [47]:
# 标准差的平方（就是方差）
np.power(log_ret.std(axis=1),2)

array([0.00131003, 0.00039359])

In [ ]:
# 矩阵的乘法是两个矩阵的协方差或余弦函数（投影）（没有标准化的协方差）

# In class practice: calculate absolute return

In [43]:
abl_ret = (arrays[:,1:]-arrays[ :,:-1])/arrays[ :,:-1]
abl_ret

array([[-0.00064475,  0.00021505,  0.03128359,  0.00941659,  0.02616179,
         0.05330426, -0.06876015],
       [ 0.01522425,  0.0157085 ,  0.01964286,  0.00075056,  0.0296875 ,
         0.03990895, -0.02670363]])

# In class practice: calculate log return

# Correlation and variance

# In class practice: Calculate Covariance Matrix Step by Step

$X$ is a $k$ by $N$ matrix, then the covariance matrix of $X$ is calculated as:
$(X-\mu)(X-\mu)^T/(N-1)$

In [48]:
log_ret.mean(axis=1,keepdims=True)

array([[0.00660943],
       [0.01317436]])

In [51]:
log_ret_demean = log_ret - log_ret.mean(axis=1,keepdims=True)


In [54]:
log_ret_demean.shape

(2, 7)

In [53]:
log_ret_demean.dot(log_ret_demean.T) / (log_ret_demean.shape[1]-1)

array([[0.00152837, 0.00078439],
       [0.00078439, 0.00045919]])

# In Class Practice Linear Regression

$Y = X\beta$

$\beta =  (X^TX)^{-1}X^TY$ 

In [ ]:
np.random.seed(5)

In [ ]:
sample_inputarray = np.random.rand( 3,20 )

# Verification